# Generated by Django 4.2.30 on 2026-06-01 14:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0227_aiapikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerateTestcaseJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DR', 'Draft'), ('QU', 'Queued'), ('AI', 'AI Generating'), ('CG', 'Compiling Generator'), ('RG', 'Running Generator'), ('CS', 'Compiling Solution'), ('RS', 'Running Solution'), ('ZP', 'Zipping'), ('IM', 'Importing'), ('DN', 'Done'), ('ER', 'Error')], default='QU', max_length=2, verbose_name='status')),
                ('id_secret', models.CharField(default=uuid.uuid4, max_length=36, unique=True, verbose_name='id secret')),
                ('ai_provider', models.CharField(blank=True, max_length=20, verbose_name='AI provider')),
                ('ai_model', models.CharField(blank=True, max_length=100, verbose_name='AI model')),
                ('generator_code', models.TextField(blank=True, default='', verbose_name='generator code')),
                ('solution_code', models.TextField(blank=True, default='', verbose_name='solution code')),
                ('num_cases', models.IntegerField(default=20, verbose_name='number of test cases')),
                ('error_stage', models.CharField(blank=True, default='', max_length=50, verbose_name='error stage')),
                ('error_log', models.TextField(blank=True, default='', verbose_name='error log')),
                ('result_testcases', models.IntegerField(blank=True, null=True, verbose_name='result test cases')),
                ('result_zip_size', models.CharField(blank=True, default='', max_length=20, verbose_name='result zip size')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generate_testcase_jobs', to='judge.problem', verbose_name='problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generate_testcase_jobs', to='judge.profile', verbose_name='user')),
            ],
            options={
                'verbose_name': 'generate testcase job',
                'verbose_name_plural': 'generate testcase jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
