# Generated by Django 4.2.30 on 2026-06-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0228_generate_testcase_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatetestcasejob',
            name='generator_code',
            field=models.TextField(blank=True, default='', verbose_name='generator code'),
        ),
        migrations.AlterField(
            model_name='generatetestcasejob',
            name='solution_code',
            field=models.TextField(blank=True, default='', verbose_name='solution code'),
        ),
        migrations.AlterField(
            model_name='generatetestcasejob',
            name='status',
            field=models.CharField(choices=[('DR', 'Draft'), ('QU', 'Queued'), ('AI', 'AI Generating'), ('CG', 'Compiling Generator'), ('RG', 'Running Generator'), ('CS', 'Compiling Solution'), ('RS', 'Running Solution'), ('ZP', 'Zipping'), ('IM', 'Importing'), ('DN', 'Done'), ('ER', 'Error')], default='QU', max_length=2, verbose_name='status'),
        ),
    ]
