# Generated by Django 4.2.30 on 2026-06-08 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0228_contest_focus_lock'),
    ]

    operations = [
        migrations.CreateModel(
            name='AICodeReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=20, verbose_name='provider')),
                ('model', models.CharField(max_length=100, verbose_name='model')),
                ('review_text', models.TextField(verbose_name='review text')),
                ('output_language', models.CharField(default='vi', max_length=20, verbose_name='output language')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_reviews', to='judge.submission', verbose_name='submission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_code_reviews', to='judge.profile', verbose_name='user')),
            ],
            options={
                'verbose_name': 'AI code review',
                'verbose_name_plural': 'AI code reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['submission', 'user'], name='judge_aicod_submiss_de02c4_idx')],
            },
        ),
    ]
