# Generated by Django 4.2.30 on 2026-06-02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0229_alter_generatetestcasejob_generator_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatetestcasejob',
            name='generator_language',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='judge.language',
                verbose_name='generator language',
            ),
        ),
        migrations.AddField(
            model_name='generatetestcasejob',
            name='solution_language',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='judge.language',
                verbose_name='solution language',
            ),
        ),
    ]
