# Generated by Django 4.2.30 on 2026-06-13 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0231_seed_ai_prompts'),
    ]

    operations = [
        migrations.CreateModel(
            name='GensolJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('GENERATING_INPUT', 'Generating Input'), ('GENERATING_OUTPUT', 'Generating Output'), ('UPLOADING', 'Uploading'), ('DONE', 'Done'), ('ERROR', 'Error')], default='PENDING', max_length=20, verbose_name='status')),
                ('generator_source', models.TextField(max_length=65536, verbose_name='generator source')),
                ('solution_source', models.TextField(max_length=65536, verbose_name='solution source')),
                ('num_cases', models.IntegerField(verbose_name='number of test cases')),
                ('current_step', models.CharField(default='generator', max_length=20, verbose_name='current step')),
                ('current_testcase', models.IntegerField(default=0, verbose_name='current test case')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='error message')),
                ('error_testcase', models.IntegerField(blank=True, null=True, verbose_name='error test case')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('generator_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='judge.language', verbose_name='generator language')),
                ('judged_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='judge.judge', verbose_name='judged on')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.problem', verbose_name='problem')),
                ('solution_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='judge.language', verbose_name='solution language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.profile', verbose_name='user')),
            ],
            options={
                'verbose_name': 'gensol job',
                'verbose_name_plural': 'gensol jobs',
                'ordering': ['-created_date'],
            },
        ),
    ]
