# Generated by Django 4.2.30 on 2026-06-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0234_contestparticipation_has_left'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemtype',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name='problem category ID'),
        ),
    ]
