# Generated by Django 4.2.30 on 2026-06-15 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0235_increase_problemtype_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProblemTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tags', to='judge.problem', verbose_name='problem')),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_tags', to='judge.submission', verbose_name='source submission')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_problem_tags', to='judge.problemtype', verbose_name='tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_tags', to='judge.profile', verbose_name='user')),
            ],
            options={
                'verbose_name': 'user problem tag',
                'verbose_name_plural': 'user problem tags',
                'indexes': [models.Index(fields=['user', 'tag'], name='judge_userp_user_id_1c1ba2_idx')],
                'unique_together': {('user', 'problem', 'tag')},
            },
        ),
    ]
