# Generated by Django 4.2.30 on 2026-06-28 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0237_update_user_problem_tag_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIGenCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=20, verbose_name='provider')),
                ('model', models.CharField(max_length=100, verbose_name='model')),
                ('num_cases', models.IntegerField(verbose_name='number of test cases')),
                ('generated_code', models.TextField(verbose_name='generated code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_gen_codes', to='judge.problem', verbose_name='problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_gen_codes', to='judge.profile', verbose_name='user')),
            ],
            options={
                'verbose_name': 'AI generated code',
                'verbose_name_plural': 'AI generated codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['problem', '-created_at'], name='judge_aigen_problem_3fd16f_idx')],
            },
        ),
    ]
