# Generated by Django 4.2.30 on 2026-07-18 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0238_add_ai_gen_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gensoljob',
            options={'ordering': ['-created_date'], 'permissions': (('generate_testcase_ai', 'Use AI Generate Testcase'),), 'verbose_name': 'gensol job', 'verbose_name_plural': 'gensol jobs'},
        ),
    ]
